const swaggerAutogen = require('swagger-autogen')();

const outputFile = './swagger_output.json'
const endpointsFiles = [
    './routes/customer-routes.js',
    './routes/login-routes.js', 
    './routes/order-routes.js',
    './routes/product-routes.js',
    './routes/user-routes.js'
]

const doc = {
    // info: General information about the API, such as: version, title and description.
    info: {
        version: "1.0.0",
        title: "Webshop API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    // host: Path and port where your API will start.
    host: "localhost:3000",
    // basePath: This is the root of your project.
    basePath: "/",
    // schemes: These are the protocols used.
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "Customer",
            "description": "CR for customer"
        }, 
        {
            "name": "Login",
            "description": "Login for the different types: User/Employee/Admin"
        }, 
        {
            "name": "Order",
            "description": "CR for order with search"
        },
        {
            "name": "Product",
            "description": "CRUD for product"
        },  
        {
            "name": "User",
            "description": "CRUD for user, with search"
        }, 
    ],
}

// rewrites the swagger_output file each time we run it with "node swagger.js"
swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./app.js')
});
