paths:
  # Create product
  /product:
    post:
      tags:
        - Products
      summary: 'Roles required: Employee, Developer or Admin'
      description: 'This is the route for creating a new product'
      produces:
      - application/json
      parameters:         # request parameters
      - in: body          # request body
        name: create product     # name of request, can be any name
        description: It enables a user to create an account
        required: true   # can also be true depending on user preference
        schema:           # Schema definition
          $ref: '#/definitions/CreateProduct' 
      responses:          # server responses
        201:
          description: ''
        500:
          description: ''
  /product/:
    get:
      tags:
        - Products
      summary: 'Roles required: Employee, Developer or Admin'
      description: 'This is the route for creating a new product'
      produces:
      - application/json
      parameters:         # request parameters
      - in: body          # request body
        name: create product     # name of request, can be any name
        description: It enables a user to create an account
        required: true   # can also be true depending on user preference
        schema:           # Schema definition
          $ref: '#/definitions/CreateProduct' 
      responses:          # server responses
        201:
          description: ''
        500:
          description: ''
  /products/:                # path of the user from your endpoint
    get:                 # endpoint request type (post request)
      tags:               # Tag property
        - Products            # Value of the tag
      summary: 'Roles required: Visitor, User, Employee, Developer or Admin'
      description: 'This is the route for getting all products'
      produces:
      - application/json
      responses:          # server responses
        200:
          description: ''
        500:
          description: ''

definitions:        # Schema defination for request body
  CreateProduct:
    type: object
    properties:
      product:
        type: object
        properties:
          username:
            type: string
            example: "Hanne"
          email:
            type: string
          password:
            type: string
